### PR TITLE
add all sqlparse.tokens.Name.Builtin types

### PR DESCRIPTION
**Pull request by lsaavedr**
Please add all builtin types from sqlparser (https://github.com/andialbrecht/sqlparse/blob/11a6b7db8b19bf1f92754a6272839c66ee630683/sqlparse/keywords.py#L630)
or match with this regex

thanks!

PD: I only need 'int' and 'double'

### CODE REVIEW

**Comment by mosi-kha** [comment]
please merge this PR and release it.
in my case, I need `array` built-in.

**Comment by xarpy** [comment]
@nesdis , please merge this PRD and release it, in my case need int format.

**Comment by mosi-kha** [comment]
@xarpy I think this repo is going to be archived because of no activity of the owner...
use [my fork](https://github.com/mosi-kha/djongo) for this issue

**Comment by xarpy** [comment]
Thank you @mosi-kha , your PR solved my problem!

**Comment by nurettin** [comment]
This is in the master branch (all types are now accepted and I guess sql generator is assumed to be correct). Thanks a lot @nesdis

**Pull request merged**
