### PR TITLE
Added jsonfield for objects/dictionaries and other unsupported MongoDB data types

### PR DESCRIPTION
**Pull request by WoLpH**
When json objects/arrays are encountered you get a pretty interface like this within the admin:

image

I don't believe there was a safe datatype to edit these types of objects before. When setting them to `TextField` or something the arrays would be replaced with a string containing `collections.OrderedDict(...)`

Note that this adds the Django-jsoneditor and Jsonfield dependencies

### CODE REVIEW

**Comment by WoLpH** [comment]
The diff without whitespace stuff: https://github.com/nesdis/djongo/pull/100/files?w=1

**Comment by WoLpH** [comment]
For the time being it only requires the small change of `get_prep_value` but I'm not entirely sure if that's the only issue. So far it seems to work nicely for me but I haven't done too extensive testing yet.

Perhaps it would be better to make it an optional dependency, similar to how the docs are an optional extra dependency: https://github.com/WoLpH/djongo/blob/8da0a6e47b77793abeef97f602f1285c157e76a3/setup.py#L80-L85

I do believe the `JSONField` is really useful when working with mongo, especially since you can easily create nested datastructures with mongo that will be very hard to represent any other way. But that's not to say it needs to be a core dependency :)

**Comment by nesdis** [comment]
Sure that makes complete sense. If you could please make that change that
would be great! Once again thank you for your contribution, your knowledge
of python is astonishing. :)

**Comment by d6tdev** [comment]
How come `JSONField` becomes `'OrderedDict()'`? It's a string not an object.

    cache = JSONField(blank=True, default={})

Becomes: ` {'cache': 'OrderedDict()')`

**Comment by WoLpH** [comment]
I can't be sure. I've been using the merged code for some time without any issues so far

**Pull request closed without merging**
